### ISSUE TITLE
Addition of log details from ahoy server

### ISSUE THREAD

**Issue by StevenLSD** [lsdopen/ahoy#9]
The application fails to deploy due to incorrect git credentials. 

history shows a failure to deploy message, but not the root cause. 

Inspecting the ahoy server pod did reveal the issue.

![image](https://user-images.githubusercontent.com/88094280/127465820-b348f07f-1f94-439d-8cb7-82099cc4d9ed.png)

**Comment by clivebor** [comment]
heys @StevenLSD

We've added ability to see the error trace on the notification description dialog and added the trace for all known and unknown errors. 

Here's a screenshot of how it looks:
![image](https://user-images.githubusercontent.com/1610577/131852161-d4336d39-0275-4163-b441-4fe1b3f55040.png)

This should help determine the root cause of failures as it includes the entire stacktrace thrown on the server.
